      - name: Upload Launcher EXE
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/launcher.exe  # Ajusta la ruta si el .exe est√° en otro lugar
          asset_name: launcher.exe
          asset_content_type: application/octet-stream